#!/bin/bash

cd generator
make clean
cd ..

cd gui
ant -q clean
cd ..

cd szakdolgozat
rm -f *.aux
rm -f *.dvi
rm -f *.gz
rm -f *.log
rm -f *.out
rm -f *.pdf
rm -f *.toc
pdflatex --interaction=batchmode -halt-on-error szakdolgozat.tex
if [ "0" != "$?"  ]; then
	exit 1
fi
pdflatex --interaction=batchmode -halt-on-error szakdolgozat.tex
if [ "0" != "$?"  ]; then
	exit 1
fi
rm -f *.aux
rm -f *.dvi
rm -f eltecimerszines*.pdf
rm -f *.gz
rm -f *.log
rm -f *.out
rm -f *.toc
cd ..

tar --exclude gui/nbproject/private -czf "szakdolgozat-$(date '+%F-%H-%M')".tar.gz generator gui szakdolgozat
