#!/bin/bash

cd scripts
./recompile
if [ "0" != "$?" ]; then
	exit 1
fi
cd ..

tar --exclude "db/*" \
	--exclude "generator/*.bin" \
	--exclude "gui/build" \
	--exclude "gui/nbproject/private" \
	-czf "szakdolgozat-$(date '+%F-%H-%M')".tar.gz db generator gui samples scripts szakdolgozat
