#!/bin/bash
rm -f primes.map
java -jar tools/dist/tools.jar seed primes.map
if [ "0" != "$?" ]; then
	exit 1
fi
COUNTER=0
while [ $COUNTER -lt 10 ]; do
	rm -f out.map
	c/simple.bin primes.map \
		$(java -jar tools/dist/tools.jar machine-info primes.map |grep end|cut -f2) \
		1073741824 out.map
	if [ "0" != "$?" ]; then
		exit 1
	fi
	java -jar tools/dist/tools.jar append primes.map out.map
	if [ "0" != "$?" ]; then
		exit 1
	fi
	rm -f out.map
	let COUNTER=COUNTER+1
done
java -jar tools/dist/tools.jar info primes.map
