#!/bin/bash

function compile {
	./compile $@
	if [ "0" != "$?" ]; then
		exit 1
	fi
	return 0
}
rm -f *.bin

for SEGMENT_BYTES in 8 128 1024 65536 131072 262144 524288
do
	compile cols-${SEGMENT_BYTES}-0 cols.c -DSEGMENT_BYTES=${SEGMENT_BYTES}
	for MIDDLE_PRIMES in 1 2 3 4 6 8
	do
		compile cols-${SEGMENT_BYTES}-${MIDDLE_PRIMES} cols.c \
			-DSEGMENT_BYTES=${SEGMENT_BYTES} -DMIDDLE_PRIMES=${MIDDLE_PRIMES}
	done
done
compile simple simple.c
exit 0
