#!/bin/bash

function compile {
	./compile $@
	if [ "0" != "$?" ]; then
		exit 1
	fi
	return 0
}

compile cols-8 cols.c -DSEGMENT_BYTES=8
compile cols-1k cols.c -DSEGMENT_BYTES=1024
compile cols-8k cols.c -DSEGMENT_BYTES=8192
compile cols-64k cols.c -DSEGMENT_BYTES=65536
compile cols-128k cols.c -DSEGMENT_BYTES=131072
compile cols-256k cols.c -DSEGMENT_BYTES=262144
compile cols-512k cols.c -DSEGMENT_BYTES=524288
compile simple simple.c
exit 0
