#!/bin/bash
SEGMENTS=1024
DB=../db

function purge {
	if [ ! -d "${1}" ]; then
		return
	fi
	for FILE in $(find ${1} -maxdepth 1 -type f -name 'primes.*' \
		! -path ${1} \
		! -path "${1}/primes.0000000000000001" \
		! -path "${1}/primes.0000000040000001" \
		! -path "${1}/primes.0000000080000001" \
		! -path ${1} ! -path "${1}/primes.00000000c0000001")
	do
		rm ${FILE}
	done
}

java -jar ../gui/dist/gui.jar database "${DB}" reaggregate
if [ "0" != "$?" ]; then
	exit 1
fi
while true
do
	purge "${DB}"
	COMMAND="../generator/$(java -jar ../gui/dist/gui.jar database "${DB}" crunch info ${SEGMENTS})"
	echo command: ${COMMAND}
	${COMMAND}
	if [ "0" != "$?" ]; then
		exit 1
	fi
	java -jar ../gui/dist/gui.jar database "${DB}" reaggregate
	if [ "0" != "$?" ]; then
		exit 1
	fi
done
exit 0
