#!/bin/bash
SEGMENTS=33
DB=../db

function database {
	java -Xms3584m -Xmx3584m -jar ../gui/dist/gui.jar database "${DB}" $@
	if [ "0" != "$?" ]; then
		exit 1
	fi
}

function purge {
	if [ ! -d "${1}" ]; then
		return
	fi
	for FILE in $(find -L ${1} -maxdepth 1 -type f -name 'primes.*' \
		! -path ${1} \
		! -path "${1}/primes.0000000000000001" \
		! -path "${1}/primes.0000000040000001" \
		! -path "${1}/primes.0000000080000001" \
		! -path ${1} ! -path "${1}/primes.00000000c0000001")
	do
		rm ${FILE}
	done
}

database reaggregate
if [ "0" != "$?" ]; then
	exit 1
fi
while true
do
	purge "${DB}"
	rm -f "${DB}/tmp.tmp"
	database info crunch ${SEGMENTS} | tee "${DB}/tmp.tmp"
	COMMAND=$(cat "${DB}/tmp.tmp"|grep "crunch: "|sed -r "s/crunch: (.*)/\\1/")
	rm -f "${DB}/tmp.tmp"
	echo command: ${COMMAND}
	${COMMAND}
	if [ "0" != "$?" ]; then
		exit 1
	fi
	database reaggregate
	if [ "0" != "$?" ]; then
		exit 1
	fi
done
exit 0
